name: Payment Service CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint || echo "No linter configured"
    
    - name: Run tests
      run: npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/payment_test
        RABBITMQ_URL: mock
        MERCADOPAGO_ACCESS_TOKEN: TEST-0000000000000000-000000-00000000000000000000000000000000-000000000
        MERCADOPAGO_WEBHOOK_URL: http://localhost:3001/api/payments/webhook

    - name: Generate code coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        flags: unittests
        name: payment-service-coverage
        fail_ci_if_error: false
        verbose: true
